#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include <cli.h>
#include <bl_gpio.h>     //  For BL602 GPIO Hardware Abstraction Layer
#include "nimble_npl.h"  //  For NimBLE Porting Layer (mulitasking functions)
#include "main_functions.h"  //  For TensorFlow Lite
#include "constants.h"       //  For Model Constants
#include "demo.h"

/// PineCone Blue LED is connected on BL602 GPIO 11
/// TODO: Change the LED GPIO Pin Number for your BL602 board
#define LED_GPIO 11

/// Command to load the TensorFlow Model (Sine Wave)
static void init(char *buf, int len, int argc, char **argv) {
    load_model();
}

/// Command to infer values with TensorFlow Model (Sine Wave)
static void infer(char *buf, int len, int argc, char **argv) {
    //  Convert the argument to float
    if (argc != 2) { printf("Usage: infer <float>\r\n"); return; }
    float input = atof(argv[1]);

    //  Run the inference
    float result = run_inference(input);

    //  Show the result
    printf("%f\r\n", result);
}

/// Command to glow the LED with values generated by the TensorFlow Model (Sine Wave).
/// We vary the LED brightness with Pulse Widge Modulation:
/// blinking the LED very rapidly with various Duty Cycle settings.
/// See https://lupyuen.github.io/articles/led#from-gpio-to-pulse-width-modulation-pwm
static void glow(char *buf, int len, int argc, char **argv) {
    //  Configure the LED GPIO for PWM
    //  pwm_init 1 11 2000
    //  int32_t bl_pwm_init(uint8_t id, uint8_t pin, uint32_t freq);

    //  Dim the LED by setting the Duty Cycle to 100%
    //  pwm_duty_set 1 100
    //  int32_t bl_pwm_set_freq(uint8_t id, uint32_t freq);

    //  Start the PWM, which will blink the LED very rapidly
    //  pwm_start 1
    //  int32_t bl_pwm_start(uint8_t id);

    //  Based on input values from 0 to 2 * Pi (stepping by 0.1)...
    for (float input = 0; input < kXrange; input += 0.1) {  //  kXrange is 2 * Pi: 6.283
        //  Infer the output value with the TensorFlow Model (Sine Wave)
        float output = run_inference(input);

        //  Output value has range -1 to 1.
        //  We sqaure the output value to produce range 0 to 1.
        float output_squared = output * output;

        //  Set the brightness (Duty Cycle) of the PWM LED to the output value squared
        //  pwm_duty_set 1 100
        //  int32_t bl_pwm_set_duty(uint8_t id, float duty);

        //  We flip the brightness because...
        //  Duty Cycle = 0% means 100% brightness
        //  Duty Cycle = 100% means 0% brightness
    }

    //  Stop the PWM, which will stop blinking the LED
    //  pwm_stop 1
    //  int32_t bl_pwm_stop( uint8_t id);
}

/// TODO: Handle math overflow.
float __math_oflowf (uint32_t sign) {
    assert(false);  //  For now, we halt when there is a math overflow
    //  Previously: return xflowf (sign, 0x1p97f);
    //  From https://code.woboq.org/userspace/glibc/sysdeps/ieee754/flt-32/math_errf.c.html#__math_oflowf
}

/// Global Destructor for C++, which we're not using.
/// See https://alex-robenko.gitbook.io/bare_metal_cpp/compiler_output/static#custom-destructors
void *__dso_handle = NULL;

///////////////////////////////////////////////////////////////////////////////
//  Command Line Interface

/// List of commands. STATIC_CLI_CMD_ATTRIBUTE makes this(these) command(s) static
const static struct cli_command cmds_user[] STATIC_CLI_CMD_ATTRIBUTE = {
    {"init",        "Init Model",        init},
    {"infer",       "Run Inference",     infer},
    {"glow",        "Glow the LED",      glow},
};                                                                                   

/// Init the command-line interface
int cli_init(void)
{
   //  To run a command at startup, do this...
   //  command_name("", 0, 0, NULL);
   return 0;
}

/// TODO: We now show assertion failures in development.
/// For production, comment out this function to use the system default,
/// which loops forever without messages.
void __assert_func(const char *file, int line, const char *func, const char *failedexpr)
{
    //  Show the assertion failure, file, line, function name
	printf("Assertion Failed \"%s\": file \"%s\", line %d%s%s\r\n",
        failedexpr, file, line, func ? ", function: " : "",
        func ? func : "");
	//  Loop forever, do not pass go, do not collect $200
	for (;;) {}
}

///////////////////////////////////////////////////////////////////////////////
//  Dump Stack

/// Dump the current stack
void dump_stack(void)
{
    //  For getting the Stack Frame Pointer. Must be first line of function.
    uintptr_t *fp;

    //  Fetch the Stack Frame Pointer. Based on backtrace_riscv from
    //  https://github.com/bouffalolab/bl_iot_sdk/blob/master/components/bl602/freertos_riscv_ram/panic/panic_c.c#L76-L99
    __asm__("add %0, x0, fp" : "=r"(fp));
    printf("dump_stack: frame pointer=%p\r\n", fp);

    //  Dump the stack, starting at Stack Frame Pointer - 1
    printf("=== stack start ===\r\n");
    for (int i = 0; i < 128; i++) {
        uintptr_t *ra = (uintptr_t *)*(unsigned long *)(fp - 1);
        printf("@ %p: %p\r\n", fp - 1, ra);
        fp++;
    }
    printf("=== stack end ===\r\n\r\n");
}

/* Output Log:

# help
====Build-in Commands====
====Support 4 cmds once, seperate by ; ====
help                     : print this
p                        : print memory
m                        : modify memory
echo                     : echo for command
exit                     : close CLI
devname                  : print device name
sysver                   : system version
reboot                   : reboot system
poweroff                 : poweroff system
reset                    : system reset
time                     : system time
ota                      : system ota
ps                       : thread dump
ls                       : file list
hexdump                  : dump file
cat                      : cat file

====User Commands====
init                     : Init Model
infer                    : Run Inference
blogset                  : blog pri set level
blogdump                 : blog info dump
bl_sys_time_now          : sys time now

# init

# infer 0.1
0.160969

# infer 0.2
0.262633

# infer 0.3
0.372770
*/